### ISSUE TITLE
[AC-10] Confluence 7.0 Compatibility (CDN Support, Guava Upgrade, Setter-Dependency-Injection Deprecation)

### ISSUE THREAD

**Issue by clouless** [codeclou/advanced-codeblocks#10]
# Story

As described in [Preparing for Confluence 7.0](https://confluence.atlassian.com/doc/preparing-for-confluence-7-0-950280675.html) many things change and we need to adapt those changes.

# Acceptance Criteria

 * ✅ Fix DI-Setter Deprecation with Confluence 7 by using `@Inject` on Properties or Constructors. Remove Setter-DI.
 * ✅ Ensure Data Center CDN Support Confluence 7
 * ✅ Fix Guava CharMatcher Deprecations in Confluence 7 and make it downward Confluence 6 compatible
 * ✅ Add more e2e tests

**Comment by clouless** [comment]
### Internal Issues

 * [ACB-INT-76] Data Center CDN Support Confluence 7
 * [ACB-INT-78] Fix DI-Setter Deprecation with Confluence 7
 * [ACB-INT-77] Guava CharMatcher.INVISIBLE deprecation in Confluence 7
 * [ACB-INT-81] More E2E Tests for core functionality

**Comment by jahdroid** [comment]
### ✅ retested on dockerized Confluence Data Center 7.0.1 Final

```
docker run  --name="confluence7" -d -p 8090:8090 -p 8091:8091 atlassian/confluence-server:7.0.1-alpine-adoptopenjdk8
```

**Comment by clouless** [comment]
### ✅ retested on dockerized Confluence Data Center 7.1.0 Final

```
docker run  --name="confluence7" -d -p 8090:8090 -p 8091:8091 atlassian/confluence-server:7.1.0-adoptopenjdk8
```
